services:
  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-Campaign}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-insecure561!$}"
      POSTGRES_DB: "${POSTGRES_DB:-CampaignTracker}"
    ports:
      - '5432:5432'
    restart: "always"
    env_file:
      - path: ".env"
        required: false
  
  django:
    build: ./Campaign-Django
    ports:
      - "8000:8000"
    command: python Campaign-Django/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      postgres:
        condition: "service_started"
    env_file:
      - path: ".env"
        required: false
  
  ember:
    build: ./Campaign-Ember
    ports: 
      - 443:80
    depends_on:
      postgres:
        condition: "service_started"
      django:
        condition: "service_started"
    

volumes:
  postgres_data: {}