services:
  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-Campaign}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-insecure561!$}"
      POSTGRES_DB: "${POSTGRES_DB:-CampaignTracker}"
    restart: always
    env_file:
      - .env.prod

  django:
    build:
      context: ./Campaign-Django
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - postgres
    env_file:
      - .env.prod

  react:
    build:
      context: ./campaign-react
      dockerfile: Dockerfile.prod
    depends_on:
      - django
    env_file:
      - .env.prod

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/usr/src/app/static
      - ./campaign-react/out:/usr/share/nginx/html:ro
    depends_on:
      - django
      - react

volumes:
  postgres_data:
  static_volume: