services:
  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-Campaign}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-insecure561!$}"
      POSTGRES_DB: "${POSTGRES_DB:-CampaignTracker}"
    ports:
      - '5432:5432'
    restart: "always"
    env_file:
      - path: ".env"
        required: false
  
  django:
    build: ./Campaign-Django
    ports:
      - "8000:8000"
    command: python Campaign-Django/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      postgres:
        condition: "service_started"
    env_file:
      - path: ".env"
        required: false
  
  #react:
  #  build: ./campaign-react
  #  ports: 
  #    - 3000:3000
  #  command: npm run dev
  #  depends_on:
  #    - django
  #  env_file:
  #    - path: ".env"
  #  environment:
  #    - NODE_ENV=development
  #    - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    

volumes:
  postgres_data: {}