services:
  django:
    build:
      context: ./Campaign-Django
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/usr/src/app/static
    env_file:
      - .env.prod
    restart: always

  react:
    build:
      context: ./campaign-react
      dockerfile: Dockerfile.prod
    depends_on:
      - django
    env_file:
      - .env.prod
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/usr/src/app/static
      - ./campaign-react/out:/usr/share/nginx/html:ro
    depends_on:
      - django
      - react
    restart: always

volumes:
  static_volume:
