FROM python:3.13.5-slim

# set a directory for the app
WORKDIR /usr/src/app

# Copy the reuirements for installation
COPY requirements.txt .

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# copy all the files to the container
COPY . .

ENV DJANGO_SETTINGS_MODULE=campaign_django.settings.production

RUN python manage.py collectstatic --noinput