# Generated by Django 5.1.1 on 2024-11-24 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignusers',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignAPI.campaigncore'),
        ),
    ]
