# Generated by Django 5.1.1 on 2024-11-04 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarcore',
            options={'verbose_name_plural': 'Calendar Cores'},
        ),
        migrations.AlterModelOptions(
            name='calevent',
            options={'verbose_name_plural': 'Calendar Events'},
        ),
        migrations.AlterModelOptions(
            name='calmonth',
            options={'verbose_name_plural': 'Calendar Months'},
        ),
        migrations.AlterModelOptions(
            name='campaigncore',
            options={'verbose_name_plural': 'Campaign Cores'},
        ),
        migrations.RenameField(
            model_name='calendarcore',
            old_name='current_age',
            new_name='current_era',
        ),
    ]
