# Generated by Django 5.1.1 on 2024-11-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumitems',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='consumitems',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hirelings',
            name='equipment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='magicitems',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='magicitems',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partymember',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payable',
            name='cp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payable',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payable',
            name='gp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payable',
            name='payee',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payable',
            name='pp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payable',
            name='sp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='cp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='gp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='pp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='sp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='equipment',
            field=models.TextField(blank=True),
        ),
    ]
