# Generated by Django 5.1.1 on 2024-11-23 23:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignAPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncore',
            name='users',
            field=models.ManyToManyField(related_name='campaign_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
