# Generated by Django 5.1.1 on 2024-11-03 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignAPI', '0002_alter_consumitems_link_alter_consumitems_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignName', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.AddField(
            model_name='consumitems',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignAPI.campaign'),
        ),
        migrations.AddField(
            model_name='hirelings',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignAPI.campaign'),
        ),
        migrations.AddField(
            model_name='magicitems',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignAPI.campaign'),
        ),
        migrations.AddField(
            model_name='partymember',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignAPI.campaign'),
        ),
        migrations.AddField(
            model_name='payable',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignAPI.campaign'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignAPI.campaign'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignAPI.campaign'),
        ),
    ]
