# Generated by Django 5.1.1 on 2024-12-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignAPI', '0004_calevent_campaign_calmonth_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncore',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
