# Generated by Django 5.1.1 on 2024-12-01 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignAPI', '0003_alter_partymember_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='calevent',
            name='campaign',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CampaignAPI.campaigncore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calmonth',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CampaignAPI.campaigncore'),
            preserve_default=False,
        ),
    ]
