# Generated by Django 5.1.1 on 2024-12-06 02:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignAPI', '0006_campaigncore_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignusers',
            unique_together={('campaign', 'user')},
        ),
    ]
