# Generated by Django 5.1.1 on 2025-07-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignAPI', '0007_alter_campaignusers_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicitems',
            name='ig_date',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
