FROM node:22-alpine as build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

RUN NEXT_DISABLE_ESLINT=true npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=build /app ./

CMD ["npm", "start"]
